algorithms:
  - name: fed_kmeans_flower
    params:
      k: [3]
      rounds: [10]

  - name: fed_fuzzy_cmeans_flower
    params:
      k: [3]
      fuzziness: [2.0]
      rounds: [10]
      tolerance: [0.0001]